---
development:
  cloud_name:  Rails.application.credentials.cloudinary.fetch(:cloud_name)
  api_key: '283319774365612'
  api_secret: t2K0_BRtyfZwd5ywAJUy5jELCBM
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dadgngbs2
  api_key: '283319774365612'
  api_secret: t2K0_BRtyfZwd5ywAJUy5jELCBM
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dadgngbs2
  api_key: '283319774365612'
  api_secret: t2K0_BRtyfZwd5ywAJUy5jELCBM
  enhance_image_tag: true
  static_file_support: false
